// Generated by CoffeeScript 1.10.0
(function() {
  var currentScroll, didScroll, hasScrolled, hideNaviIfNeeded, showNavi;

  currentScroll = 0;

  didScroll = false;

  setInterval(function() {
    if (didScroll) {
      hasScrolled();
      return didScroll = false;
    }
  }, 250);

  hasScrolled = function() {
    if ($(this).scrollTop() < currentScroll) {
      showNavi();
    } else {
      hideNaviIfNeeded();
    }
    return currentScroll = $(this).scrollTop();
  };

  showNavi = (function(_this) {
    return function() {
      $('#navigation').removeClass('is-hidden');
      return $('#navigation').addClass('is-visible');
    };
  })(this);

  hideNaviIfNeeded = function() {
    if (currentScroll > 100) {
      $('#navigation').addClass('is-hidden');
      return $('#navigation').removeClass('is-visible');
    }
  };

  (function($) {})(jQuery);

  $(window).scroll(function(event) {
    return didScroll = true;
  });

}).call(this);
