name: Create Registration from Issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Authenticate Git
      run: |
        echo "machine github.com login codefreeze-registrations password ${GITHUB_TOKEN}" > ~/.netrc
        git status
        git config user.email "actions@example.com"
        git config user.name "GitHub Actions"
    - uses: codefreezefi/registration-action@saga
